### ISSUE TITLE
[REQUEST] Community Mascot

### ISSUE THREAD

**Issue by LePichu** [trynova/nova#390]
Node has a Turtle for a Mascot, Deno has a Dinosaur, Bun has, well, an edible Bun, how about a Nova mascot? ~~I'd vote for a Cat mascot~~

**Comment by aapoalas** [comment]
Those three you mentioned are runtimes, not engines. Perhaps you meant to request this of Andromeda?

On the engine side, V8 has their logo and JSC has a logo as well I think? We also kind of have a logo or three.
